<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[DB Connected]]>
    </line>
    <line>
      <![CDATA[Browser Launched]]>
    </line>
    <line>
      <![CDATA[Logged into the Application ]]>
    </line>
    <line>
      <![CDATA[addRestaurant----->TestScript Execution Started]]>
    </line>
    <line>
      <![CDATA[TestScript Execution Skipped]]>
    </line>
    <line>
      <![CDATA[Logged out of the Application ]]>
    </line>
    <line>
      <![CDATA[Logged into the Application ]]>
    </line>
    <line>
      <![CDATA[addRestaurant----->TestScript Execution Started]]>
    </line>
    <line>
      <![CDATA[TestScript Execution Skipped]]>
    </line>
    <line>
      <![CDATA[Logged out of the Application ]]>
    </line>
    <line>
      <![CDATA[Logged into the Application ]]>
    </line>
    <line>
      <![CDATA[addRestaurant----->TestScript Execution Started]]>
    </line>
    <line>
      <![CDATA[TestScript Execution Skipped]]>
    </line>
    <line>
      <![CDATA[Logged out of the Application ]]>
    </line>
    <line>
      <![CDATA[Logged into the Application ]]>
    </line>
    <line>
      <![CDATA[addRestaurant----->TestScript Execution Started]]>
    </line>
    <line>
      <![CDATA[TestScript Execution Failed]]>
    </line>
    <line>
      <![CDATA[Logged out of the Application ]]>
    </line>
    <line>
      <![CDATA[Browser Closed]]>
    </line>
    <line>
      <![CDATA[DB disConnected ]]>
    </line>
  </reporter-output>
  <suite started-at="2023-03-29T14:54:45 IST" name="Default suite" finished-at="2023-03-29T14:55:12 IST" duration-ms="27173">
    <groups>
      <group name="Smoke">
        <method signature="RestaurantTest.addRestaurant()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" name="addRestaurant" class="testngpractise.RestaurantTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-03-29T14:54:45 IST" name="Default test" finished-at="2023-03-29T14:55:12 IST" duration-ms="27173">
      <class name="testngpractise.RestaurantTest">
        <test-method is-config="true" signature="configBS()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:54:45 IST" name="configBS" finished-at="2023-03-29T14:54:45 IST" duration-ms="409" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[DB Connected]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:54:46 IST" name="configBC" finished-at="2023-03-29T14:54:50 IST" duration-ms="4584" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser Launched]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:54:50 IST" name="configBM" finished-at="2023-03-29T14:54:53 IST" duration-ms="2617" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged into the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="addRestaurant()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:54:53 IST" name="addRestaurant" finished-at="2023-03-29T14:54:53 IST" duration-ms="22" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testngpractise.RestaurantTest.addRestaurant(RestaurantTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addRestaurant----->TestScript Execution Started]]>
            </line>
            <line>
              <![CDATA[TestScript Execution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- addRestaurant -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:54:53 IST" name="configAM" finished-at="2023-03-29T14:55:01 IST" duration-ms="7610" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out of the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:01 IST" name="configBM" finished-at="2023-03-29T14:55:02 IST" duration-ms="981" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged into the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="addRestaurant()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:02 IST" name="addRestaurant" finished-at="2023-03-29T14:55:02 IST" duration-ms="5" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testngpractise.RestaurantTest.addRestaurant(RestaurantTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addRestaurant----->TestScript Execution Started]]>
            </line>
            <line>
              <![CDATA[TestScript Execution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- addRestaurant -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:02 IST" name="configAM" finished-at="2023-03-29T14:55:05 IST" duration-ms="3518" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out of the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:05 IST" name="configBM" finished-at="2023-03-29T14:55:06 IST" duration-ms="885" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged into the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="addRestaurant()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:06 IST" name="addRestaurant" finished-at="2023-03-29T14:55:06 IST" duration-ms="2" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testngpractise.RestaurantTest.addRestaurant(RestaurantTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addRestaurant----->TestScript Execution Started]]>
            </line>
            <line>
              <![CDATA[TestScript Execution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- addRestaurant -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:06 IST" name="configAM" finished-at="2023-03-29T14:55:08 IST" duration-ms="2508" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out of the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:08 IST" name="configBM" finished-at="2023-03-29T14:55:09 IST" duration-ms="857" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged into the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="addRestaurant()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:09 IST" name="addRestaurant" finished-at="2023-03-29T14:55:09 IST" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testngpractise.RestaurantTest.addRestaurant(RestaurantTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addRestaurant----->TestScript Execution Started]]>
            </line>
            <line>
              <![CDATA[TestScript Execution Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- addRestaurant -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:10 IST" name="configAM" finished-at="2023-03-29T14:55:12 IST" duration-ms="2741" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out of the Application ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAF()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:12 IST" name="configAF" finished-at="2023-03-29T14:55:12 IST" duration-ms="194" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser Closed]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAF -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:testngpractise.RestaurantTest@37d4349f]" started-at="2023-03-29T14:55:13 IST" name="configAS" finished-at="2023-03-29T14:55:13 IST" duration-ms="19" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[DB disConnected ]]>
            </line>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- testngpractise.RestaurantTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
